# Generated by Django 4.0.3 on 2024-02-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
