# Generated by Django 4.0.3 on 2024-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(default='DEFAULT_VIN', max_length=200),
        ),
    ]
